/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frc1318_apriltag_AprilTagDetector */

#ifndef _Included_frc1318_apriltag_AprilTagDetector
#define _Included_frc1318_apriltag_AprilTagDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frc1318_apriltag_AprilTagDetector
 * Method:    detect
 * Signature: (JJ)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_frc1318_apriltag_AprilTagDetector_detect
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     frc1318_apriltag_AprilTagDetector
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_frc1318_apriltag_AprilTagDetector_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
