/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frc1318_apriltag_AprilTag */

#ifndef _Included_frc1318_apriltag_AprilTag
#define _Included_frc1318_apriltag_AprilTag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frc1318_apriltag_AprilTag
 * Method:    createDetector
 * Signature: (IIIFFZDZ)J
 */
JNIEXPORT jlong JNICALL Java_frc1318_apriltag_AprilTag_createDetector
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jboolean, jdouble, jboolean);

#ifdef __cplusplus
}
#endif
#endif
