/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frc1318_ws2812_WS2812LedStrip */

#ifndef _Included_frc1318_ws2812_WS2812LedStrip
#define _Included_frc1318_ws2812_WS2812LedStrip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frc1318_ws2812_WS2812LedStrip
 * Method:    createStrip
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_frc1318_ws2812_WS2812LedStrip_createStrip
  (JNIEnv *, jclass, jint);

/*
 * Class:     frc1318_ws2812_WS2812LedStrip
 * Method:    open
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_frc1318_ws2812_WS2812LedStrip_open
  (JNIEnv *, jclass, jlong);

/*
 * Class:     frc1318_ws2812_WS2812LedStrip
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_frc1318_ws2812_WS2812LedStrip_release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     frc1318_ws2812_WS2812LedStrip
 * Method:    blank
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_frc1318_ws2812_WS2812LedStrip_blank
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     frc1318_ws2812_WS2812LedStrip
 * Method:    setColor
 * Signature: (JIBBB)V
 */
JNIEXPORT void JNICALL Java_frc1318_ws2812_WS2812LedStrip_setColor__JIBBB
  (JNIEnv *, jclass, jlong, jint, jbyte, jbyte, jbyte);

/*
 * Class:     frc1318_ws2812_WS2812LedStrip
 * Method:    setColor
 * Signature: (JIIBBB)V
 */
JNIEXPORT void JNICALL Java_frc1318_ws2812_WS2812LedStrip_setColor__JIIBBB
  (JNIEnv *, jclass, jlong, jint, jint, jbyte, jbyte, jbyte);

/*
 * Class:     frc1318_ws2812_WS2812LedStrip
 * Method:    render
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_frc1318_ws2812_WS2812LedStrip_render
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
